# Numpy
-----
## 03. 배열 연산과 함수
### 텍스트 파일 다루기
- savetxt : 배열을 텍스트 파일로 저장
- loadtxt : 텍스트 파일을 배열로 불러오기

In [16]:
import numpy as np

data = np.random.rand(5, 3)
print(data)

# 텍스트  파일로 저장 
np.savetxt('mynumpydata.txt', data)    # 공백으로 구분
# np.savetxt('mynumpydata.txt', data, delimiter=",")    # ,로 구분(CSV)
# 텍스트 파일을 배열로 불러오기
# load_data = np.loadtxt('data.txt')
load_data = np.loadtxt('mynumpydata.txt')
print(load_data)

[[0.27949049 0.48198269 0.04049797]
 [0.88784596 0.77012137 0.25977784]
 [0.10877646 0.17714965 0.34129503]
 [0.25415517 0.41349535 0.13658766]
 [0.16901778 0.85864572 0.95507223]]
[[0.27949049 0.48198269 0.04049797]
 [0.88784596 0.77012137 0.25977784]
 [0.10877646 0.17714965 0.34129503]
 [0.25415517 0.41349535 0.13658766]
 [0.16901778 0.85864572 0.95507223]]


### 바이너리 파일 다루기
- save : 배열을 바이너리 파일로 저장
    - 넘파이 배열의 확장자는 .npy
- load : 바이너리 파일을 배열로 불러오기

※ 바이너리 형식으로 데이터를 저장하고 불러오면 데이터 손실 없이 빠르게 처리할 수 있으므로, 크기가 크고 복잡한 데이터를 다룰 때 특히 유용

In [17]:
import numpy as np
import os
# 가상의 데이터 생성
data = np.random.rand(5, 3)
print("data :\n", data)
# 데이터를 바이너리 형식으로 저장
# if not os.path.exists('../generated'):
#     os.makedirs('../generated')
np.save('mybindata', data)

load_data = np.load('mybindata.npy')
print("load_data :\n", load_data)

data :
 [[0.2595408  0.73319329 0.76825673]
 [0.4441187  0.42087026 0.80538645]
 [0.81237511 0.64159739 0.69148451]
 [0.37242571 0.05362045 0.45098614]
 [0.94354716 0.7438838  0.80356475]]
load_data :
 [[0.2595408  0.73319329 0.76825673]
 [0.4441187  0.42087026 0.80538645]
 [0.81237511 0.64159739 0.69148451]
 [0.37242571 0.05362045 0.45098614]
 [0.94354716 0.7438838  0.80356475]]
